//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab29MovieAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
		//internal string movieID;

		public int ID { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
    }
}
